=== plecmaciej/Simple-webpage/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="hipertext" type="hipertextType"/>  
	<xs:complexType name="hipertextType">
		<xs:sequence>
			<xs:element name="autor" type="autorType" /> 	
			<xs:element name="tytul" type="tytulType"/>   
			<xs:element name="artysci" type="artysciType"/>
		</xs:sequence>
	</xs:complexType>

    <xs:element name="zdjecie" type="daneType"/>
	<xs:element name="strona" type="daneType"/>

    <xs:complexType name="daneType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="krotkiType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dlugiType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="70"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="autorType">
		<xs:sequence>
			<xs:element name="imie" type="krotkiType" />		
			<xs:element name="nazwisko" type="krotkiType" />	
	</xs:complexType>

    <xs:simpleType name="tytulType"> 					
		<xs:restriction base="xs:string">
			<xs:minLength value="6"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="artysciType">
		<xs:sequence>
			<xs:element name="artysta" type="artystaType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="artystaType">
	<xs:complexContent>
		<xs:extension base="autorType">
            <xs:sequence>
                    <xs:element name="rokurodzenia" type="xs:gYear" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="roksmierci" type="xs:gYear" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="informacje" type="xs:string"/>
                    <xs:element ref="zdjecie"/>
                    <xs:element ref="strona"/>
                    <xs:element name="koncerty">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="koncert" type="koncertType" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                    </xs:element>
            </xs:sequence>
		<xs:attribute name="zyje" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="tak"/>
					<xs:enumeration value="nie"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		</xs:extension>
	</xs:complexContent>
	</xs:complexType>
    
	<xs:complexType name="koncertType">
		<xs:sequence>
			<xs:element name="data" type="date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="godzina" type="time" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ocena" type="double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="n"/>
	</xs:complexType>


</xs:schema>

=== plecmaciej/Simple-webpage/index.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="index.xsd">
	<autor>
		<imie>Maciej</imie>
		<nazwisko>Plec</nazwisko>
	</autor>
	<tytuł>
		Najwieksi artysci
	</tytuł>
	<artysci>
		<artysta zyje="tak">
			<imie>Zenon </imie>
			<nazwisko>Martyniuk</nazwisko>
            <pseudonim>Zenek</pseudonim>
			<rokurodzenia>1970</rokurodzenia>
			<informacje>
		        Listę nie mogl rozpoczac nikt inny jak najslynniejszy spiewak w polsce. Swoją kariere zaczal
                tak dawno ze ciezko zapamietac kiedy. Wazne natomiast jest to ze zdecydowanie blyszczy jako 
                gwiazda sylwestra w tvp gdzie co roku spiewa swoj najwiekszy hit o pszczołach i historii o 
                swoim pobycie w zakladzie psychiatrycznym po tym jak oszalał na punkcie zielonych gałek ocznych. 
                Zdecydowanie wzor do nasladowania.
			</informacje>
			<zdjecie source="photo\zenek.jpg">Zenon Martyniuk</zdjecie>
			<strona source="https://www.zespolakcent.pl">Zenon Martyniuk</strona>
			<koncerty>
				<koncert n="1">
					<data>16.8</data>
					<godzina>17.00</godzina>
					<ocena>10</ocena>
				</koncert>
                <koncert n="2">
					<data>16.8</data>
					<godzina>17.00</godzina>
					<ocena>10</ocena>
				</koncert>
                <koncert n="3">
					<data>16.8</data>
					<godzina>17.00</godzina>
					<ocena>10</ocena>
				</koncert>
			</koncerty>
		</artysta>
		<artysta zyje="tak">
			<imie>Patryk </imie>
			<nazwisko>Wozinski</nazwisko>
            <pseudonim>Kizo</pseudonim>
			<rokurodzenia>1990</rokurodzenia>
			<informacje>
		        Pisząc ten tekst nie mam zamiaru się smucić tylko zatracić w tym co najlepsze. 
                Kizo to artysta z Gdańska dzięki czemu wie że ludzie chcą się kłócić chcą nas zdusić
                 jakby to było konieczne. Poza tym jest też biznesmenem ma swoją markę kaw, pizz,
                  batonów nie tylko ona mu ufa daje mu rękę wszystko zamienia w bajeczne. Ponadto
                   nasz grajek nagrywa seriale i jest wszechstronnie rozwiniety więc niech trwa jeszcze
                    hotelowa doba w apartamencie. Ten artysta kiedys nie mial a teraz ma.
			</informacje>
			<zdjecie source="photo\kizo.jpg">Zenon Martyniuk</zdjecie>
			<strona source="https://www.zespolakcent.pl">Zenon Martyniuk</strona>
			<koncerty>
				<koncert n="1">
					<data>26.9</data>
					<godzina>15.00</godzina>
					<ocena>9.0</ocena>
				</koncert>
                <koncert n="2">
					<data>2.2</data>
					<godzina>12.00</godzina>
					<ocena>6.0</ocena>
				</koncert>
			</koncerty>
		</artysta>
        <artysta zyje="tak">
			<imie>Krystian </imie>
			<nazwisko>Pudzianowski</nazwisko>
            <pseudonim>Brat pudziana</pseudonim>
			<rokurodzenia>1980</rokurodzenia>
			<informacje>
		        Pudzian band to zdecydwowanie najwiekszy zespół z jakim mialem stycznosc. 
                Tworzy go brat najwiekszego Polaka w historii - Krystian Pudzianowski.
                 W przeciwieństwie do brata Krystian zamiast łapać i rzucać zaczął karierę muzyczną.
                  Tanio skóry nie sprzedał ale swoje płyty już tak, dzięki czemu wystąpił na 
                  stadionie narodowym przed walką Mariusza z Testosteronem.
			</informacje>
			<zdjecie source="photo\pudzian.jpg">Zenon Martyniuk</zdjecie>
			<strona source="https://www.zespolakcent.pl">Zenon Martyniuk</strona>
			<koncerty>
				<koncert n="1">
					<data>19.8</data>
					<godzina>15.00</godzina>
					<ocena>2.0</ocena>
				</koncert>
                <koncert n="2">
					<data>7.2</data>
					<godzina>13.00</godzina>
					<ocena>10</ocena>
				</koncert>
                <koncert n="3">
					<data>12.8</data>
					<godzina>17.00</godzina>
					<ocena>3.5</ocena>
				</koncert>
                <koncert n="4">
					<data>16.8</data>
					<godzina>3.00</godzina>
					<ocena>8.5</ocena>
				</koncert>
			</koncerty>
		</artysta>
	</artysci>
</hipertext>
